### ISSUE TITLE
Can be better

### ISSUE THREAD

**Issue by Xflick** [DamnTricker996/Code---1#2]
The program can be better in the following aspects:
1. Input check can be added in.
2. When inputting the number, the user have to input like "1\n 2\n 3\n", and in my opinion, the user is supposed to input "123" without hitting the enter.
3. When generating the random number, you use while(true) { if (...) break; }. Actually, we can use do while(...) instead.
4. The style of coding is not so good. Like in line 52, this line is far too long!!! And some names of variable can also be changed, such as:number_matched-position_matched.
But ignoring these aspects, the program works well.

**Comment by Xflick** [comment]
Errr... I have found another bug. When entering "N", I cannot quit the program.

**Comment by DamnTricker996** [comment]
All I think necessary has been corrected, thank you for all of this.
